// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTyC7s61q8Mlgg60Ri0MQrxOQFPYo3qtI',
    appId: '1:861454959980:web:235f0712f79f8f2a57df49',
    messagingSenderId: '861454959980',
    projectId: 'flash-chat-944c4',
    authDomain: 'flash-chat-944c4.firebaseapp.com',
    storageBucket: 'flash-chat-944c4.firebasestorage.app',
    measurementId: 'G-DLL512LY11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYEil8YCO4SxU1pwGRIBbbPGNoLO28nWI',
    appId: '1:861454959980:android:5330ae237c6f633257df49',
    messagingSenderId: '861454959980',
    projectId: 'flash-chat-944c4',
    storageBucket: 'flash-chat-944c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxcJ0aKOv0FWRAvpyAvzIToPof_LhtWA',
    appId: '1:861454959980:ios:f5219f5188a637ff57df49',
    messagingSenderId: '861454959980',
    projectId: 'flash-chat-944c4',
    storageBucket: 'flash-chat-944c4.firebasestorage.app',
    iosBundleId: 'com.example.flashChattt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxcJ0aKOv0FWRAvpyAvzIToPof_LhtWA',
    appId: '1:861454959980:ios:f5219f5188a637ff57df49',
    messagingSenderId: '861454959980',
    projectId: 'flash-chat-944c4',
    storageBucket: 'flash-chat-944c4.firebasestorage.app',
    iosBundleId: 'com.example.flashChattt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTyC7s61q8Mlgg60Ri0MQrxOQFPYo3qtI',
    appId: '1:861454959980:web:4ffba088deeb651a57df49',
    messagingSenderId: '861454959980',
    projectId: 'flash-chat-944c4',
    authDomain: 'flash-chat-944c4.firebaseapp.com',
    storageBucket: 'flash-chat-944c4.firebasestorage.app',
    measurementId: 'G-G6ZDJ3VSQR',
  );

}